// src/react/useContainerQuery.ts
"use client";

import { type RefObject, useEffect, useState } from "react";
import {
  type ContainerSize,
  getContainerSize,
  matchesContainerRange,
  observeContainer,
} from "../core/container.js";

export interface ContainerQueryRange {
  minPx?: number;
  maxPx?: number;
}

/**
 * SSR-safe container-query hook. Returns whether the element matches the
 * given range. Uses ResizeObserver under the hood with a frame-throttled
 * callback to avoid loop-limit errors.
 */
export function useContainerQuery(
  ref: RefObject<Element | null>,
  range: ContainerQueryRange,
  serverDefault = false,
  options: { debounce?: number; throttle?: number } = {},
): boolean {
  const [matches, setMatches] = useState<boolean>(serverDefault);
  const minPx = range.minPx;
  const maxPx = range.maxPx;

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const r = { minPx, maxPx };
    setMatches(matchesContainerRange(getContainerSize(el), r));
    const unsub = observeContainer(el, (size) => {
      setMatches(matchesContainerRange(size, r));
    }, options);
    return unsub;
  }, [ref, minPx, maxPx, options.debounce, options.throttle]);

  return matches;
}

/** Get the current container size (re-rendering on changes). */
export function useContainerSize(
  ref: RefObject<Element | null>,
  serverDefault: ContainerSize = { width: 0, height: 0 },
  options: { debounce?: number; throttle?: number } = {},
): ContainerSize {
  const [size, setSize] = useState<ContainerSize>(serverDefault);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setSize(getContainerSize(el));
    return observeContainer(el, setSize, options);
  }, [ref, options.debounce, options.throttle]);
  return size;
}

// src/solid/useContainerQuery.ts
import { type Accessor, createEffect, createSignal, onCleanup, onMount } from "solid-js";
import {
  type ContainerSize,
  getContainerSize,
  matchesContainerRange,
  observeContainer,
} from "../core/container.js";

export interface ContainerQueryRange {
  minPx?: number;
  maxPx?: number;
}

type ContainerTarget = Element | null | undefined;
type MaybeAccessor<T> = T | Accessor<T>;

function resolveTarget(target: MaybeAccessor<ContainerTarget>) {
  return typeof target === "function" ? (target as Accessor<ContainerTarget>)() : target;
}

export function useContainerQuery(
  target: MaybeAccessor<ContainerTarget>,
  range: ContainerQueryRange,
  serverDefault = false,
  options: { debounce?: number; throttle?: number } = {},
): Accessor<boolean> {
  const [matches, setMatches] = createSignal(serverDefault);

  onMount(() => {
    createEffect(() => {
      const element = resolveTarget(target);
      const currentRange = { minPx: range.minPx, maxPx: range.maxPx };

      if (!element) {
        setMatches(serverDefault);
        return;
      }

      setMatches(matchesContainerRange(getContainerSize(element), currentRange));
      const unsubscribe = observeContainer(
        element,
        (size) => {
          setMatches(matchesContainerRange(size, currentRange));
        },
        options,
      );

      onCleanup(unsubscribe);
    });
  });

  return matches;
}

export interface UseContainerSizeResult {
  size: Accessor<ContainerSize>;
  width: Accessor<number>;
  height: Accessor<number>;
}

export function useContainerSize(
  target: MaybeAccessor<ContainerTarget>,
  serverDefault: ContainerSize = { width: 0, height: 0 },
  options: { debounce?: number; throttle?: number } = {},
): UseContainerSizeResult {
  const [size, setSize] = createSignal(serverDefault);

  onMount(() => {
    createEffect(() => {
      const element = resolveTarget(target);

      if (!element) {
        setSize(serverDefault);
        return;
      }

      setSize(getContainerSize(element));
      const unsubscribe = observeContainer(
        element,
        (nextSize) => {
          setSize(nextSize);
        },
        options,
      );

      onCleanup(unsubscribe);
    });
  });

  return {
    size,
    width: () => size().width,
    height: () => size().height,
  };
}
