// src/qwik/useResponsiveValue.ts
import { type Signal, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import type { BreakpointMap } from "../core/breakpoints.js";
import { type ResponsiveValue, resolveResponsive } from "../core/responsive-value.js";
import { useFluidityContext } from "./context.js";

export function useResponsiveValue<T, B extends BreakpointMap>(
  value: ResponsiveValue<T, B>,
): Signal<T | undefined> {
  const { store, system } = useFluidityContext();
  const result = useSignal<T | undefined>(undefined);

  useVisibleTask$(({ cleanup }) => {
    const sync = () => {
      const snap = store.getSnapshot();
      result.value = resolveResponsive(
        system as unknown as Parameters<typeof resolveResponsive<T, B>>[0],
        value,
        snap.width,
      );
    };
    sync();
    const unsubscribe = store.subscribe(sync);
    cleanup(unsubscribe);
  });

  return result;
}

// src/solid/useResponsiveValue.ts
import { type Accessor, createSignal, onCleanup, onMount } from "solid-js";
import type { BreakpointMap } from "../core/breakpoints.js";
import { type ResponsiveValue, resolveResponsive } from "../core/responsive-value.js";
import { useFluidityContext } from "./context.js";

/**
 * Resolve a responsive value (`T | Partial<Record<BreakpointKey, T>>`) to
 * the value matching the current breakpoint, with mobile-first fallback.
 */
export function useResponsiveValue<T, B extends BreakpointMap>(
  value: ResponsiveValue<T, B>,
): Accessor<T | undefined> {
  const { store, system } = useFluidityContext<B>();
  const [result, setResult] = createSignal<T | undefined>(
    resolveResponsive(
      system as unknown as Parameters<typeof resolveResponsive<T, B>>[0],
      value,
      store.getSnapshot().width,
    ),
  );

  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    setResult(() =>
      resolveResponsive(
        system as unknown as Parameters<typeof resolveResponsive<T, B>>[0],
        value,
        store.getSnapshot().width,
      ),
    );
    unsubscribe = store.subscribe(() => {
      setResult(() =>
        resolveResponsive(
          system as unknown as Parameters<typeof resolveResponsive<T, B>>[0],
          value,
          store.getSnapshot().width,
        ),
      );
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  return result;
}
