// src/qwik/useViewport.ts
import { type Signal, useComputed$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { useFluidityContext } from "./context.js";

export interface ViewportState {
  width: number;
  height: number;
  orientation: "portrait" | "landscape";
}

export function useViewport(): {
  width: Signal<number>;
  height: Signal<number>;
  orientation: Signal<"portrait" | "landscape">;
} {
  const { store } = useFluidityContext();
  const serverSnapshot = store.getServerSnapshot();
  const snapshot = useSignal<ViewportState>({
    width: serverSnapshot.width,
    height: serverSnapshot.height,
    orientation: serverSnapshot.orientation,
  });

  useVisibleTask$(({ cleanup }) => {
    const sync = () => {
      const next = store.getSnapshot();
      snapshot.value = {
        width: next.width,
        height: next.height,
        orientation: next.orientation,
      };
    };

    sync();
    const unsubscribe = store.subscribe(sync);
    cleanup(unsubscribe);
  });

  return {
    width: useComputed$(() => snapshot.value.width),
    height: useComputed$(() => snapshot.value.height),
    orientation: useComputed$(() => snapshot.value.orientation),
  };
}

// src/solid/useViewport.ts
import { type Accessor, createSignal, onCleanup, onMount } from "solid-js";
import { useFluidityContext } from "./context.js";

export interface ViewportState {
  width: number;
  height: number;
  orientation: "portrait" | "landscape";
}

export interface UseViewportResult {
  width: Accessor<number>;
  height: Accessor<number>;
  orientation: Accessor<"portrait" | "landscape">;
}

export function useViewport(): UseViewportResult {
  const { store } = useFluidityContext();
  const [snapshot, setSnapshot] = createSignal(store.getSnapshot());
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    setSnapshot(store.getSnapshot());
    unsubscribe = store.subscribe(() => {
      setSnapshot(store.getSnapshot());
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  return {
    width: () => snapshot().width,
    height: () => snapshot().height,
    orientation: () => snapshot().orientation,
  };
}
