// src/qwik/useElementSize.ts
import { type Signal, useComputed$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { type ContainerSize, getContainerSize, observeContainer } from "../core/container.js";

type ElementTarget = Signal<Element | null | undefined>;

export type UseElementSizeResult = { width: number; height: number };

export function useElementSize(
  target: ElementTarget,
  serverDefault: UseElementSizeResult = { width: 0, height: 0 },
  options: { debounce?: number; throttle?: number } = {},
): { width: Signal<number>; height: Signal<number> } {
  const size = useSignal<ContainerSize>({ ...serverDefault });

  useVisibleTask$(({ track, cleanup }) => {
    const element = track(() => target.value);

    if (!element) {
      size.value = { ...serverDefault };
      return;
    }

    size.value = getContainerSize(element);
    const unsubscribe = observeContainer(
      element,
      (nextSize) => {
        size.value = nextSize;
      },
      options,
    );

    cleanup(unsubscribe);
  });

  return {
    width: useComputed$(() => size.value.width),
    height: useComputed$(() => size.value.height),
  };
}

// src/react/useElementSize.ts
"use client";

import { type RefObject, useEffect, useState } from "react";
import { getContainerSize, observeContainer, type ContainerSize } from "../core/container.js";

export type UseElementSizeResult = { width: number; height: number };

const DEFAULT_SIZE: UseElementSizeResult = { width: 0, height: 0 };

export function useElementSize(
  ref: RefObject<Element | null>,
  serverDefault: UseElementSizeResult = DEFAULT_SIZE,
  options: { debounce?: number; throttle?: number } = {},
): UseElementSizeResult {
  const [size, setSize] = useState<UseElementSizeResult>(serverDefault);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    setSize(getContainerSize(el));
    const unsub = observeContainer(
      el,
      (s: ContainerSize) => setSize({ width: s.width, height: s.height }),
      options,
    );
    return unsub;
  }, [ref, options]);

  return size;
}
