// src/solid/useContainerQuery.ts
import { type Accessor, createEffect, createSignal, onCleanup, onMount } from "solid-js";
import {
  type ContainerSize,
  getContainerSize,
  matchesContainerRange,
  observeContainer,
} from "../core/container.js";

export interface ContainerQueryRange {
  minPx?: number;
  maxPx?: number;
}

type ContainerTarget = Element | null | undefined;
type MaybeAccessor<T> = T | Accessor<T>;

function resolveTarget(target: MaybeAccessor<ContainerTarget>) {
  return typeof target === "function" ? (target as Accessor<ContainerTarget>)() : target;
}

export function useContainerQuery(
  target: MaybeAccessor<ContainerTarget>,
  range: ContainerQueryRange,
  serverDefault = false,
): Accessor<boolean> {
  const [matches, setMatches] = createSignal(serverDefault);

  onMount(() => {
    createEffect(() => {
      const element = resolveTarget(target);
      const currentRange = { minPx: range.minPx, maxPx: range.maxPx };

      if (!element) {
        setMatches(serverDefault);
        return;
      }

      setMatches(matchesContainerRange(getContainerSize(element), currentRange));
      const unsubscribe = observeContainer(element, (size) => {
        setMatches(matchesContainerRange(size, currentRange));
      });

      onCleanup(unsubscribe);
    });
  });

  return matches;
}

export interface UseContainerSizeResult {
  size: Accessor<ContainerSize>;
  width: Accessor<number>;
  height: Accessor<number>;
}

export function useContainerSize(
  target: MaybeAccessor<ContainerTarget>,
  serverDefault: ContainerSize = { width: 0, height: 0 },
): UseContainerSizeResult {
  const [size, setSize] = createSignal(serverDefault);

  onMount(() => {
    createEffect(() => {
      const element = resolveTarget(target);

      if (!element) {
        setSize(serverDefault);
        return;
      }

      setSize(getContainerSize(element));
      const unsubscribe = observeContainer(element, (nextSize) => {
        setSize(nextSize);
      });

      onCleanup(unsubscribe);
    });
  });

  return {
    size,
    width: () => size().width,
    height: () => size().height,
  };
}

// src/qwik/useContainerQuery.ts
import { type Signal, useComputed$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import {
  type ContainerSize,
  getContainerSize,
  matchesContainerRange,
  observeContainer,
} from "../core/container.js";

export interface ContainerQueryRange {
  minPx?: number;
  maxPx?: number;
}

type ContainerTarget = Signal<Element | null | undefined>;

export function useContainerQuery(
  target: ContainerTarget,
  range: ContainerQueryRange,
  serverDefault = false,
): Signal<boolean> {
  const matches = useSignal(serverDefault);

  useVisibleTask$(({ track, cleanup }) => {
    const element = track(() => target.value);

    if (!element) {
      matches.value = serverDefault;
      return;
    }

    const currentRange = { minPx: range.minPx, maxPx: range.maxPx };
    matches.value = matchesContainerRange(getContainerSize(element), currentRange);

    const unsubscribe = observeContainer(element, (size) => {
      matches.value = matchesContainerRange(size, currentRange);
    });

    cleanup(unsubscribe);
  });

  return matches;
}

export function useContainerSize(
  target: ContainerTarget,
  serverDefault: ContainerSize = { width: 0, height: 0 },
): { width: Signal<number>; height: Signal<number> } {
  const size = useSignal<ContainerSize>({ ...serverDefault });

  useVisibleTask$(({ track, cleanup }) => {
    const element = track(() => target.value);

    if (!element) {
      size.value = { ...serverDefault };
      return;
    }

    size.value = getContainerSize(element);
    const unsubscribe = observeContainer(element, (nextSize) => {
      size.value = nextSize;
    });

    cleanup(unsubscribe);
  });

  return {
    width: useComputed$(() => size.value.width),
    height: useComputed$(() => size.value.height),
  };
}
