// src/solid/useDevicePixelRatio.ts
import { type Accessor, createSignal, onCleanup, onMount } from "solid-js";
import { isServer } from "solid-js/web";
import { getDevicePixelRatio, observeDevicePixelRatio } from "../core/dpr.js";

export function useDevicePixelRatio(serverDefault = 1): Accessor<number> {
  const [devicePixelRatio, setDevicePixelRatio] = createSignal(
    isServer ? serverDefault : getDevicePixelRatio(),
  );
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    setDevicePixelRatio(getDevicePixelRatio());
    unsubscribe = observeDevicePixelRatio((next) => {
      setDevicePixelRatio(next);
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  return devicePixelRatio;
}

// src/qwik/useDevicePixelRatio.ts
import { type Signal, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { getDevicePixelRatio, observeDevicePixelRatio } from "../core/dpr.js";

export function useDevicePixelRatio(serverDefault = 1): Signal<number> {
  const dpr = useSignal(serverDefault);

  useVisibleTask$(({ cleanup }) => {
    dpr.value = getDevicePixelRatio();
    const unsubscribe = observeDevicePixelRatio((next) => {
      dpr.value = next;
    });

    cleanup(unsubscribe);
  });

  return dpr;
}
