// src/react/usePointer.ts
"use client";

import { mq } from "../core/media.js";
import { useMediaQuery } from "./useMediaQuery.js";

/** Pointer and hover capabilities for the current device. */
export interface PointerInfo {
  hover: boolean;
  anyHover: boolean;
  coarse: boolean;
  fine: boolean;
}

/** Detect pointer capabilities (hover, touch, fine). SSR-safe with configurable defaults. */
export function usePointer(serverDefault?: Partial<PointerInfo>): PointerInfo {
  return {
    hover: useMediaQuery(mq.hover, serverDefault?.hover ?? true),
    anyHover: useMediaQuery(mq.anyHover, serverDefault?.anyHover ?? true),
    coarse: useMediaQuery(mq.coarseCursor, serverDefault?.coarse ?? false),
    fine: useMediaQuery(mq.fineCursor, serverDefault?.fine ?? true),
  };
}

// src/qwik/usePointer.ts
import type { Signal } from "@builder.io/qwik";
import { mq } from "../core/media.js";
import { useMediaQuery } from "./useMediaQuery.js";

export interface PointerInfo {
  hover: Signal<boolean>;
  anyHover: Signal<boolean>;
  coarse: Signal<boolean>;
  fine: Signal<boolean>;
}

export function usePointer(
  serverDefault?: Partial<{ hover: boolean; anyHover: boolean; coarse: boolean; fine: boolean }>,
): PointerInfo {
  return {
    hover: useMediaQuery(mq.hover, serverDefault?.hover ?? true),
    anyHover: useMediaQuery(mq.anyHover, serverDefault?.anyHover ?? true),
    coarse: useMediaQuery(mq.coarseCursor, serverDefault?.coarse ?? false),
    fine: useMediaQuery(mq.fineCursor, serverDefault?.fine ?? true),
  };
}
