// src/solid/useSafeArea.ts
import { type Accessor, createSignal, onCleanup, onMount } from "solid-js";
import { isServer } from "solid-js/web";
import { type SafeAreaInsets, getSafeArea, observeSafeArea } from "../core/safe-area.js";

const ZERO: SafeAreaInsets = { top: 0, right: 0, bottom: 0, left: 0 };

export interface UseSafeAreaResult {
  insets: Accessor<SafeAreaInsets>;
  top: Accessor<number>;
  right: Accessor<number>;
  bottom: Accessor<number>;
  left: Accessor<number>;
}

export function useSafeArea(serverDefault: SafeAreaInsets = ZERO): UseSafeAreaResult {
  const [insets, setInsets] = createSignal<SafeAreaInsets>(
    isServer ? serverDefault : getSafeArea(),
  );
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    setInsets(getSafeArea());
    unsubscribe = observeSafeArea((nextInsets) => {
      setInsets(nextInsets);
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  return {
    insets,
    top: () => insets().top,
    right: () => insets().right,
    bottom: () => insets().bottom,
    left: () => insets().left,
  };
}

// src/qwik/useSafeArea.ts
import { type Signal, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import { type SafeAreaInsets, getSafeArea, observeSafeArea } from "../core/safe-area.js";

const ZERO: SafeAreaInsets = { top: 0, right: 0, bottom: 0, left: 0 };

export function useSafeArea(serverDefault: SafeAreaInsets = ZERO): Signal<SafeAreaInsets> {
  const insets = useSignal<SafeAreaInsets>({ ...serverDefault });

  useVisibleTask$(({ cleanup }) => {
    insets.value = getSafeArea();
    const unsubscribe = observeSafeArea((next) => {
      insets.value = next;
    });

    cleanup(unsubscribe);
  });

  return insets;
}
